source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasySpotlight_Example', :exclusive => true do
  pod "EasySpotlight", :path => "../"
end

target 'EasySpotlight_Tests', :exclusive => true do
  pod "EasySpotlight", :path => "../"

pod 'Quick', :git => "https://github.com/Quick/Quick", :branch => "swift-2.0"
pod 'Nimble', :git => "https://github.com/Quick/Nimble", :branch => "swift-2.0"
end
